Repository SauloVrS/Tier, pull requests merged in 2022-05, with the labels that each got.

#14 [TIER-01] Tela lojas (principal)
  lib/data/banners.dart
  lib/data/lojas.dart
  lib/data/produtos.dart
  lib/data/promocoes.dart
  lib/data/servicos.dart
  lib/main.dart
  lib/models/loja_model.dart
  lib/models/produto_model.dart
  lib/views/main_lojas.dart
  lib/widgets/banners.dart
  lib/widgets/bottom_nav_bar.dart
  lib/widgets/lojas_list.dart
  lib/widgets/promocoes_list.dart
  lib/widgets/servicos_produtos_list.dart
Labels: enhancement

#17 Splash Screen e Tela de Busca
  images/img.png
  lib/main.dart
  lib/views/busca_principal.dart
  lib/views/splash_screen.dart
  lib/widgets/bottom_nav_bar.dart
  lib/widgets/busca_widget.dart
  lib/widgets/carroussel_image.dart
  lib/widgets/experimente_buscar.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#20 Tier 01 ray- tela de configuração
  lib/views/configuracoes_pages/ajuda.dart
  lib/views/configuracoes_pages/cadastre_sua_loja.dart
  lib/views/configuracoes_pages/idiomas.dart
  lib/views/configuracoes_pages/politicas_de_uso.dart
  lib/views/configuracoes_pages/sobre.dart
  lib/views/configuracoes_perfil.dart
  lib/views/perfil_usuario.dart
  pubspec.lock
Labels: enhancement, good first issue

#29 Lagumas funções do Firestore - Firebase
  android/app/build.gradle
  android/app/google-services.json
  android/build.gradle
  lib/firebase/firestore_tier.dart
  lib/firebase/user.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: documentation, enhancement

#32 Correção do cabeçalho na página da loja
  lib/views/loja_page.dart
Labels: enhancement

#36 Tela de Produtos e Tela de Lojas (Busca)
  images/imagem_loja_racao.jpg
  images/loja_racao1.jpg
  images/loja_racao4.jpg
  images/loja_racao_novo.jpg
  lib/views/busca_principal.dart
  lib/views/itens.dart
  lib/views/lista_itens.dart
  lib/views/lista_lojas.dart
  lib/widgets/busca_widget.dart
  lib/widgets/loja_widget.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#44 Criação das duas primeiras tela do carrinho e firebase
  images/carrinho_vazio.png
  lib/views/carrinho/carrinho_inicial.dart
  lib/views/main_lojas.dart
  lib/views/produto_page.dart
  lib/widgets/carrinho_widgets/carrinho_functions.dart
  lib/widgets/carrinho_widgets/carrinho_itens.dart
  lib/widgets/carrinho_widgets/carrinho_vazio.dart
  lib/widgets/carrinho_widgets/helper_pedido.dart
  lib/widgets/carrinho_widgets/icon_carrinho.dart
  lib/widgets/carrinho_widgets/metodo_pagamento.dart
  lib/widgets/carrinho_widgets/modal_excluir_item.dart
  lib/widgets/carrinho_widgets/modal_loja_diferente.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#48 Funcionamento da tela de busca
  lib/views/itens.dart
  lib/views/lista_itens.dart
  lib/views/lista_lojas.dart
  lib/widgets/busca_widget.dart
  lib/widgets/buscar_functions/busca_functions.dart
Labels: enhancement
